# Generated by Django 4.1.3 on 2022-12-16 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='contact',
            name='first_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='last_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.TextField(blank=True),
        ),
    ]
