# Generated by Django 4.1.3 on 2022-12-14 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anagramgame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_length', models.CharField(choices=[(5, '5'), (6, '6'), (7, '7'), (8, '8')], default=5, max_length=1)),
                ('score', models.IntegerField()),
                ('end_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Anagram',
        ),
    ]
