# Generated by Django 4.1.3 on 2023-02-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagram', '0004_rename_end_time_anagramgame_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anagramgame',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='anagramgame',
            name='word_length',
            field=models.CharField(choices=[(5, '5'), (6, '6'), (7, '7'), (8, '8')], default='5', max_length=1),
        ),
    ]
