# Generated by Django 4.1.3 on 2023-02-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagram', '0006_alter_anagramgame_word_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anagramgame',
            name='word_length',
            field=models.IntegerField(choices=[(5, 5), (6, 6), (7, 7), (8, 8)], default=5, max_length=1),
        ),
    ]
