# Generated by Django 4.1.3 on 2022-12-08 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathgame', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MathScore',
            new_name='Mathgame',
        ),
    ]
