# Generated by Django 4.1.3 on 2022-12-21 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mathgame', '0003_mathgame_end_time_mathgame_max_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathgame',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
