# Generated by Django 4.1.3 on 2022-12-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathgame', '0004_mathgame_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathgame',
            name='answer',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mathgame',
            name='max_number',
            field=models.IntegerField(default=10),
        ),
    ]
