# Generated by Django 4.1.3 on 2022-12-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathgame', '0005_mathgame_answer_alter_mathgame_max_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathgame',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mathgame',
            name='operation',
            field=models.CharField(choices=[('+', 'Addition'), ('-', 'Subtraction'), ('*', 'Multiplication'), ('/', 'Division')], default='+', max_length=1),
        ),
    ]
