# Generated by Django 4.1.3 on 2022-12-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathgame', '0006_mathgame_slug_alter_mathgame_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathgame',
            name='score',
            field=models.IntegerField(blank=True),
        ),
    ]
