# Generated by Django 4.1.3 on 2022-12-28 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathgame', '0007_alter_mathgame_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathgame',
            name='slug',
            field=models.SlugField(default='scr', editable=False, unique=True),
            preserve_default=False,
        ),
    ]
