# Generated by Django 4.1.3 on 2022-12-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathgame', '0008_alter_mathgame_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathgame',
            name='answer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mathgame',
            name='end_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='mathgame',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
