# Generated by Django 4.1.3 on 2022-12-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathgame', '0011_alter_mathgame_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathgame',
            name='category',
            field=models.CharField(default='Math Facts Practice', max_length=50),
        ),
    ]
