# Generated by Django 4.1.3 on 2023-01-03 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathgame', '0013_alter_mathgame_operation_alter_mathgame_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathgame',
            name='time_left',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='mathgame',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
