# Generated by Django 4.1.3 on 2023-01-04 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathgame', '0014_mathgame_time_left_alter_mathgame_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game_num',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num1', models.IntegerField()),
                ('num2', models.IntegerField()),
            ],
        ),
    ]
