# Generated by Django 4.1.3 on 2023-01-04 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathgame', '0015_game_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game_num',
            name='num1',
        ),
        migrations.RemoveField(
            model_name='game_num',
            name='num2',
        ),
    ]
