# Generated by Django 4.1.3 on 2023-01-04 20:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mathgame', '0018_gameplay_delete_game_num_remove_mathgame_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathgame',
            name='correct_answer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mathgame',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mathgame',
            name='incorrect_answer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mathgame',
            name='num1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mathgame',
            name='num2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mathgame',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mathgame',
            name='time_left',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='mathgame',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='gameplay',
            name='num1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gameplay',
            name='num2',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
