# Generated by Django 4.1.3 on 2023-01-04 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathgame', '0019_mathgame_correct_answer_mathgame_created_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gameplay',
        ),
    ]
