# Generated by Django 4.1.3 on 2023-01-11 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathgame', '0020_delete_gameplay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mathgame',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='mathgame',
            name='incorrect_answer',
        ),
        migrations.RemoveField(
            model_name='mathgame',
            name='num1',
        ),
        migrations.RemoveField(
            model_name='mathgame',
            name='num2',
        ),
        migrations.RemoveField(
            model_name='mathgame',
            name='time_left',
        ),
    ]
