# Generated by Django 4.1.3 on 2023-01-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathgame', '0021_remove_mathgame_correct_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathgame',
            name='score',
            field=models.IntegerField(),
        ),
    ]
