# Generated by Django 4.1.3 on 2023-01-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathgame', '0024_remove_mathgame_score_mathgamescore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathgamescore',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
