# Generated by Django 4.1.3 on 2023-01-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathgame', '0025_alter_mathgamescore_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mathgamescore',
            old_name='score',
            new_name='scores',
        ),
        migrations.AddField(
            model_name='mathgame',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
